"""
OmniBrain Database and Vector Store Module.
Exposes database models, session factories, vector store, and system-wide Pydantic schemas/DTOs.
"""

from .database import (
    Base,
    engine,
    AsyncSessionLocal,
    get_db,
    init_db,
    close_db,
)
from .models import (
    User,
    Document,
    ChatSession,
    ChatMessage,
    AuditLog,
)
from .vector_store import (
    QdrantVectorStore,
    vector_store,
)
from .schemas import (
    # Auth & User Schemas
    UserRole,
    UserBase,
    UserCreate,
    UserCreateRequest,
    UserLogin,
    UserUpdate,
    UserRead,
    UserRecord,
    UserResponse,
    Token,
    TokenResponse,
    TokenData,
    
    # Document Ingestion DTOs
    DocumentStatus,
    DocumentBase,
    DocumentCreate,
    DocumentRead,
    DocumentRecord,
    DocumentMetadata,
    DocumentChunk,
    DocumentSummary,
    DocumentListResponse,
    UploadResponse,
    JobStatusResponse,
    DocumentIngestionRequest,
    DocumentIngestionResponse,
    DocumentSummaryResponse,
    
    # Citation DTOs
    CitationSource,
    Citation,
    
    # Chat DTOs
    MessageRole,
    ChatMessageCreate,
    ChatMessageResponse,
    ChatSessionCreate,
    ChatSessionUpdate,
    ChatSessionResponse,
    MessageRecord,
    HistoryResponse,
    ChatRequest,
    ChatResponse,
    ChatQueryRequest,
    ChatQueryResponse,
    
    # Vector Search DTOs
    VectorSearchType,
    VectorSearchFilter,
    VectorSearchQuery,
    VectorSearchResult,
    VectorUpsertRequest,
    VectorUpsertResponse,
    
    # Audit & Health
    AuditLogCreate,
    AuditLogResponse,
    HealthCheckResponse,
    SystemHealth,
    SystemMetricsResponse,
    TelemetryMetrics,
    AdminActionResponse,
)

__all__ = [
    # Database core
    "Base",
    "engine",
    "AsyncSessionLocal",
    "get_db",
    "init_db",
    "close_db",
    # Vector Store
    "QdrantVectorStore",
    "vector_store",
    # ORM Models
    "User",
    "Document",
    "ChatSession",
    "ChatMessage",
    "AuditLog",
    # Pydantic Schemas / DTOs
    "UserRole",
    "UserBase",
    "UserCreate",
    "UserCreateRequest",
    "UserLogin",
    "UserUpdate",
    "UserRead",
    "UserRecord",
    "UserResponse",
    "Token",
    "TokenResponse",
    "TokenData",
    "DocumentStatus",
    "DocumentBase",
    "DocumentCreate",
    "DocumentRead",
    "DocumentRecord",
    "DocumentMetadata",
    "DocumentChunk",
    "DocumentSummary",
    "DocumentListResponse",
    "UploadResponse",
    "JobStatusResponse",
    "DocumentIngestionRequest",
    "DocumentIngestionResponse",
    "DocumentSummaryResponse",
    "CitationSource",
    "Citation",
    "MessageRole",
    "ChatMessageCreate",
    "ChatMessageResponse",
    "ChatSessionCreate",
    "ChatSessionUpdate",
    "ChatSessionResponse",
    "MessageRecord",
    "HistoryResponse",
    "ChatRequest",
    "ChatResponse",
    "ChatQueryRequest",
    "ChatQueryResponse",
    "VectorSearchType",
    "VectorSearchFilter",
    "VectorSearchQuery",
    "VectorSearchResult",
    "VectorUpsertRequest",
    "VectorUpsertResponse",
    "AuditLogCreate",
    "AuditLogResponse",
    "HealthCheckResponse",
    "SystemHealth",
    "SystemMetricsResponse",
    "TelemetryMetrics",
    "AdminActionResponse",
]